SECTION_DEFINITIONS = [
    {
        "key": "abstract",
        "display_name": "Abstract",
        "order": 10,
        "aliases": {
            "abstract",
            "summary",
            "özet",
        },
        "section_type": "front_matter",
        "requires_number": False,
        "should_summarize": True,
    },
    {
        "key": "acknowledgements",
        "display_name": "Acknowledgements",
        "order": 15,
        "aliases": {
            "acknowledgement",
            "acknowledgements",
            "acknowledgment",
            "acknowledgments",
            "teşekkür",
            "teşekkürler",
        },
        "section_type": "front_matter",
        "requires_number": False,
        "should_summarize": False,
    },
    {
        "key": "introduction",
        "display_name": "Introduction",
        "order": 20,
        "aliases": {
            "introduction",
            "general introduction",
            "giriş",
        },
        "section_type": "body",
        "requires_number": False,
        "should_summarize": True,
    },
    {
        "key": "literature_review",
        "display_name": "Literature Review",
        "order": 30,
        "aliases": {
            "literature review",
            "review of literature",
            "related work",
            "related works",
            "related literature",
            "background",
            "theoretical background",
            "conceptual background",
            "literatür taraması",
            "literatür incelemesi",
            "ilgili çalışmalar",
            "kuramsal çerçeve",
        },
        "section_type": "body",
        "requires_number": False,
        "should_summarize": True,
    },
    {
        "key": "methodology",
        "display_name": "Methodology",
        "order": 40,
        "aliases": {
            "methodology",
            "methods",
            "method",
            "research methods",
            "research methodology",
            "materials and methods",
            "materials and method",
            "material and methods",
            "materials and methodologies",
            "experimental methods",
            "experimental procedure",
            "experimental procedures",
            "study design",
            "research design",
            "materials",
            "yöntem",
            "yöntemler",
            "araştırma yöntemi",
            "materyal ve metot",
            "materyal ve yöntem",
            "gereç ve yöntem",
        },
        "section_type": "body",
        "requires_number": False,
        "should_summarize": True,
    },
    {
        "key": "results",
        "display_name": "Results",
        "order": 50,
        "aliases": {
            "results",
            "findings",
            "experimental results",
            "research findings",
            "results and findings",
            "results and discussion",
            "findings and discussion",
            "experimental results and discussion",
            "analysis of results",
            "bulgular",
            "sonuçlar",
            "deneysel sonuçlar",
            "bulgular ve tartışma",
            "sonuçlar ve tartışma",
        },
        "section_type": "body",
        "requires_number": False,
        "should_summarize": True,
    },
    {
        "key": "discussion",
        "display_name": "Discussion",
        "order": 60,
        "aliases": {
            "discussion",
            "general discussion",
            "discussion and implications",
            "discussion and analysis",
            "interpretation of findings",
            "tartışma",
            "değerlendirme",
            "genel değerlendirme",
        },
        "section_type": "body",
        "requires_number": False,
        "should_summarize": True,
    },
    {
        "key": "conclusion",
        "display_name": "Conclusions",
        "order": 70,
        "aliases": {
            "conclusion",
            "conclusions",
            "summary and conclusion",
            "summary and conclusions",
            "general conclusions",
            "conclusions and recommendations",
            "conclusion and recommendations",
            "closing remarks",
            "sonuç",
            "sonuçlar",
            "genel sonuçlar",
            "sonuç ve öneriler",
            "sonuçlar ve öneriler",
        },
        "section_type": "body",
        "requires_number": False,
        "should_summarize": True,
    },
    {
        "key": "future_work",
        "display_name": "Future Work",
        "order": 80,
        "aliases": {
            "future work",
            "future studies",
            "future research",
            "recommendations",
            "recommendations for future studies",
            "recommendations for future research",
            "future directions",
            "limitations and future work",
            "limitations and recommendations",
            "gelecek çalışmalar",
            "gelecek araştırmalar",
            "öneriler",
            "gelecek çalışmalar için öneriler",
        },
        "section_type": "body",
        "requires_number": False,
        "should_summarize": True,
    },
    {
        "key": "references",
        "display_name": "References",
        "order": 90,
        "aliases": {
            "references",
            "references cited",
            "bibliography",
            "works cited",
            "kaynaklar",
            "kaynakça",
        },
        "section_type": "back_matter",
        "requires_number": False,
        "should_summarize": False,
    },
    {
        "key": "appendix",
        "display_name": "Appendix",
        "order": 100,
        "aliases": {
            "appendix",
            "appendices",
            "appendix a",
            "appendix b",
            "supplementary material",
            "supplementary materials",
            "ek",
            "ekler",
        },
        "section_type": "back_matter",
        "requires_number": False,
        "should_summarize": False,
    },
]