SECTION_DEFINITIONS = [
    {
        "key": "abstract",
        "display_name": "Abstract",
        "order": 10,
        "aliases": {
            "abstract",
            "özet",
        },
        "section_type": "front_matter",
        "requires_number": False,
        "should_summarize": True,
    },
    {
        "key": "introduction",
        "display_name": "Introduction",
        "order": 20,
        "aliases": {
            "introduction",
            "giriş",
        },
        "section_type": "body",
        "requires_number": True,
        "should_summarize": True,
    },
    {
        "key": "overview",
        "display_name": "Overview",
        "order": 30,
        "aliases": {
            "overview",
            "background",
            "background and related work",
            "general overview",
            "genel bakış",
        },
        "section_type": "body",
        "requires_number": True,
        "should_summarize": True,
    },
    {
        "key": "user_analysis",
        "display_name": "User Analysis",
        "order": 40,
        "aliases": {
            "understanding user diversity in emergency mobile applications",
            "understanding user diversity",
            "user analysis",
            "participant analysis",
            "kullanıcı analizi",
        },
        "section_type": "body",
        "requires_number": True,
        "should_summarize": True,
    },
    {
    "key": "results",
    "display_name": "Results",
    "order": 50,
    "aliases": {
        "results",
        "findings",
        "results and findings",
        "results: technology use and communication channels questionnaire",
        "results technology use and communication channels questionnaire",
        "technology use and communication channels questionnaire results",
        "questionnaire results",
        "sonuçlar",
        "bulgular",
    },
    "section_type": "body",
    "requires_number": True,
    "should_summarize": True,
    },
    {
        "key": "discussion",
        "display_name": "Discussion",
        "order": 60,
        "aliases": {
            "discussion",
            "discussion and implications",
            "tartışma",
            "değerlendirme",
        },
        "section_type": "body",
        "requires_number": True,
        "should_summarize": True,
    },
    {
        "key": "requirements",
        "display_name": "Requirements Proposal",
        "order": 70,
        "aliases": {
            "requirements proposal",
            "proposed requirements",
            "requirements",
            "requirement framework",
            "gereksinim önerisi",
            "gereksinimler",
        },
        "section_type": "body",
        "requires_number": True,
        "should_summarize": True,
    },
    {
        "key": "conclusion",
        "display_name": "Conclusions",
        "order": 80,
        "aliases": {
            "conclusion",
            "conclusions",
            "conclusion and future work",
            "conclusions and future work",
            "sonuç",
            "sonuçlar",
            "sonuç ve gelecek çalışmalar",
        },
        "section_type": "body",
        "requires_number": True,
        "should_summarize": True,
    },
    {
        "key": "appendix",
        "display_name": "Appendix",
        "order": 90,
        "aliases": {
            "appendix",
            "appendix a",
            "appendices",
            "ek",
            "ekler",
        },
        "section_type": "back_matter",
        "requires_number": False,
        "should_summarize": False,
    },
    {
        "key": "references",
        "display_name": "References",
        "order": 100,
        "aliases": {
            "references",
            "bibliography",
            "kaynaklar",
            "kaynakça",
        },
        "section_type": "back_matter",
        "requires_number": False,
        "should_summarize": False,
    },
]